### ISSUE TITLE
Cannot setup country/region for DST account

### ISSUE THREAD

**Issue by lzhangcs** [hms-ecosystem/Calculator-App#6]
[ads.huawei.com_5_18_2022.har.zip](https://github.com/hms-ecosystem/Calculator-App/files/8719189/ads.huawei.com_5_18_2022.har.zip)

**Comment by bryantvu** [comment]
I am not HQ, I cannot read or undersstand .HAR files.

**Comment by lzhangcs** [comment]
DTSE requests this issue to be resolved for his App Life Cycle feature.  This is the log file for HQ to debug.  HQ  investigation is in progress. No worries.

**Comment by bryantvu** [comment]
I've confirmed that these fiiles can be passed to HQ with no issue.
